# Generated by Django 3.0.7 on 2020-06-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handel_method', models.CharField(choices=[('a', '不通知'), ('a', '弹窗警告'), ('b', '邮箱通知'), ('c', '短信通知')], default='a', max_length=1, verbose_name='通知方法')),
                ('handel_cause', models.CharField(choices=[('a', '正常'), ('b', '异常'), ('c', '温度过高'), ('d', '损坏')], default='a', max_length=1, verbose_name='机器故障类型')),
            ],
        ),
    ]
