# Generated by Django 3.0.7 on 2020-06-12 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(blank=True, max_length=128, null=True)),
                ('method', models.CharField(blank=True, max_length=128, null=True)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device', verbose_name='设备')),
                ('log_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile', verbose_name='管理员')),
            ],
        ),
    ]
